// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClZIknczTLuKol17oZtsc4qw3GB3xcoaw',
    appId: '1:773850325802:web:34e5ae646c3512dce9b453',
    messagingSenderId: '773850325802',
    projectId: 'myfitzoneapp',
    authDomain: 'myfitzoneapp.firebaseapp.com',
    storageBucket: 'myfitzoneapp.firebasestorage.app',
    measurementId: 'G-5SSEBEY86P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDeKMUymzmhPE_eaLJRMjyMQ2VUau1KJQ',
    appId: '1:773850325802:android:42553b9287523cb7e9b453',
    messagingSenderId: '773850325802',
    projectId: 'myfitzoneapp',
    storageBucket: 'myfitzoneapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALCtom9RgIDeB1rc5VcNdew4R-oylumpA',
    appId: '1:773850325802:ios:9a34fe453ccbb2d4e9b453',
    messagingSenderId: '773850325802',
    projectId: 'myfitzoneapp',
    storageBucket: 'myfitzoneapp.firebasestorage.app',
    iosBundleId: 'com.example.fitzoneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALCtom9RgIDeB1rc5VcNdew4R-oylumpA',
    appId: '1:773850325802:ios:9a34fe453ccbb2d4e9b453',
    messagingSenderId: '773850325802',
    projectId: 'myfitzoneapp',
    storageBucket: 'myfitzoneapp.firebasestorage.app',
    iosBundleId: 'com.example.fitzoneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClZIknczTLuKol17oZtsc4qw3GB3xcoaw',
    appId: '1:773850325802:web:6c36b5977942d8dfe9b453',
    messagingSenderId: '773850325802',
    projectId: 'myfitzoneapp',
    authDomain: 'myfitzoneapp.firebaseapp.com',
    storageBucket: 'myfitzoneapp.firebasestorage.app',
    measurementId: 'G-4DTEC7C2RW',
  );
}
